// Generated by GitHub Actions. The shared team key is embedded so the root URL works without a query string.
window.APP_CONFIG = {
  MANTLE_BASE_URL: "https://mantledb.sh/v2",
  TEAM_TOKEN: "eyJuIjoid2VzdGZvbGQtYmVuY2h3YXJtZXJzLTMzMThhNTMzOThiMjIyN2YiLCJrIjoiMGIzZmMzMTFiZDBlZTliYmNlMGY1MzkwOWNlYzQxYjlhNzU0MjNhNWUwYTVkNGM5NDlhNDIzYWE0YzJjZTQ2MCJ9",
  VAPID_PUBLIC_KEY: "BOPZ2_gba0kOKb9lhAPeKxDey20v45T5TbWTldjXeaPKaZ73Az-aEQcNsZpq57Fsv1CBGS3NhpsDSl0OaqNKWVQ",
  SUPABASE_URL: "https://westfold.local",
  SUPABASE_PUBLISHABLE_KEY: "mantle-adapter"
};
